- name: Upgrade kibana
  hosts: kibana
  serial: 1
  become: true
  roles:
    - role: upgrade_elastic_tool
  vars:
    elastic_component: kibana

- name: Upgrade and reboot
  hosts: kibana
  serial: 1
  become: true
  roles:
    - role: upgrade_and_reboot