- name: Upgrade elasticsearch
  hosts: elasticsearch
  order: inventory
  become: true
  serial: 1
  roles:
    - role: get_elasticsearch_version
      vars:
        elastic_hostname: "{{ inventory_hostname }}"
    - role: upgrade_and_check_available_version
      vars:
        package_name: elasticsearch
    - role: upgrade_elastic_nodes
