- name: Get cluster version
  hosts: fleet
  vars:
    elastic_user: elastic
    elastic_password: secretpassword
    elastic_node: 10.0.10.12
  tasks:
    - shell: curl -ks https://{{ elastic_node }}:9200 -u "{{ elastic_user }}:{{ elastic_password }}" | jq -r '.version.number'
      register: current_elasticsearch_version
    - name: Print current elastic version
      ansible.builtin.debug:
        msg: "{{ current_elasticsearch_version }}"

- name: Upgrade fleet and artifact registry
  hosts: fleet
  become: true
  environment:
    STACK_VERSION: "{{ current_elasticsearch_version.stdout }}"
    DOWNLOAD_BASE_DIR: /opt/elastic-packages
  roles:
    - role: upgrade_fleet_artifact_registry

- name: Upgrade and reboot
  hosts: fleet
  become: true
  roles:
    - role: upgrade_and_reboot