- name: Upgrade kibana
  hosts: kibana
  serial: 1
  become: true
  roles:
    - role: get_yum_available_packages
      vars:
        package_name: kibana.x86_64
    - role: upgrade_elastic_tool
      vars:
        elastic_component: kibana