- name: Upgrade logstash
  hosts: logstash
  serial: 1
  become: true
  roles:
    - role: get_yum_available_packages
      vars:
        package_name: logstash.x86_64
    - role: upgrade_elastic_tool
      vars:
        elastic_component: logstash