- name: Get current and available elasticsearch version
  hosts: elasticsearch
  run_once: true
  become: true
  roles:
    - role: get_elasticsearch_version

- name: Upgrade fleet and artifact registry
  hosts: fleet
  become: true
  roles:
    - role: upgrade_fleet_artifact_registry

- name: Upgrade and reboot
  hosts: fleet
  become: true
  roles:
    - role: upgrade_and_reboot