- name: Get current and available elasticsearch version
  hosts: elasticsearch
  run_once: true
  become: true
  roles:
    - role: get_elasticsearch_version

- name: Upgrade elasticsearch
  hosts: elasticsearch
  serial: 1
  become: true
  roles:
    - role: upgrade_elastic_nodes

- name: Upgrade and reboot
  hosts: elasticsearch
  serial: 1
  become: true
  roles:
    - role: upgrade_and_reboot_elasticsearch