# ToDo: fix variables
- name: Upgrade fleet
  hosts: fleet
  become: true
  #pre_tasks:
  #  - shell: curl -s https://{{ elastic_node }}:9200 -u "{{ elastic_user }}:{{ elastic_password }}" | jq -r '.version.number'
  #    register: current_elasticsearch_version
  roles:
    - role: upgrade_fleet_artifact_registry
      #vars:
      #  - elasticsearch_version: "{{ current_elasticsearch_version.stdout }}"
    - role: upgrade_and_reboot
    