- name: Get current and available elasticsearch version
  hosts: elasticsearch
  run_once: true
  become: true
  roles:
    - role: get_elasticsearch_version

- name: Upgrade elasticsearch
  hosts: elasticsearch
  serial: 1
  become: true
  roles:
    - role: upgrade_elastic_nodes
  when:
    "'Available packages' in available_elasticsearch_packages.stdout"
  #vars:
  #  current_elasticsearch_version: "{{ current_elasticsearch_version.stdout }}"

- name: Upgrade and reboot
  hosts: elasticsearch
  serial: 1
  become: true
  roles:
    - role: upgrade_and_reboot