- name: Upgrade logstash
  hosts: logstash
  serial: 1
  become: true
  roles:
    - role: upgrade_elastic_tool
  vars:
    elastic_component: logstash

- name: Upgrade and reboot
  hosts: logstash
  serial: 1
  become: true
  roles:
    - role: upgrade_and_reboot