- name: Upgrade fleet
  hosts: fleet
  become: true
  vars:
    DOWNLOAD_BASE_DIR: "/opt/elastic-packages"
    ARTIFACT_DOWNLOADS_BASE_URL: "https://artifacts.elastic.co/downloads"
    COMMON_PACKAGE_PREFIXES:
      - "apm-server/apm-server"
      - "beats/auditbeat/auditbeat"
      - "beats/elastic-agent/elastic-agent"
      - "beats/filebeat/filebeat"
      - "beats/heartbeat/heartbeat"
      - "beats/metricbeat/metricbeat"
      - "beats/osquerybeat/osquerybeat"
      - "beats/packetbeat/packetbeat"
      - "endpoint-dev/endpoint-security"
      - "fleet-server/fleet-server"
    WIN_ONLY_PACKAGE_PREFIXES:
      - "beats/winlogbeat/winlogbeat"
    RPM_PACKAGES:
      - "beats/elastic-agent/elastic-agent"
      - "cloudbeat/cloudbeat"
    DEB_PACKAGES:
      - "beats/elastic-agent/elastic-agent"
      - "cloudbeat/cloudbeat"
  roles:
    - role: get_elasticsearch_version
      vars:
        elastic_hostname: "{{ elastic_node }}"
    - role: upgrade_fleet_artifact_registry
      vars:
        linux_distribution: RedHat
        STACK_VERSION: "{{ current_elasticsearch_version }}"
      #when: "'linux' in ansible_play_hosts"
    #- role: upgrade_and_reboot
    