- name: update all packages (please be patient)
  yum:
    name: '*'
    state: latest
  register: yum_updates

- name: check if reboot is required
  shell:
    cmd: "needs-restarting -r"
  failed_when: reboot_required.rc != 0 and reboot_required.rc != 1
  register: reboot_required

- name: reboot host
  reboot:
    reboot_timeout: 300
  when: reboot_required.rc == 1