- name: update all packages (please be patient)
  yum:
    name: '*'
    state: latest
  register: yum_updates

- name: reboot host
  reboot:
    reboot_timeout: 300
  when: yum_updates.changes.updated|flatten|select('regex', '^kernel$') is any