- name: update all packages (please be patient)
  yum:
    name: '*'
    state: latest
    exclude: "{{ package_name }}.x86_64"
  register: yum_updates

# - name: check if reboot is required
#   shell:
#     cmd: "needs-restarting -r"
#   failed_when: reboot_required.rc != 0 and reboot_required.rc != 1
#   register: reboot_required

- name: remove yum versionlock
  community.general.yum_versionlock:
    state: absent
    name: "{{ package_name }}"

- name: check available versions
  yum:
    name: "{{ package_name }}.x86_64"
    state: latest
  check_mode: true
  register: yum_latest_versions

- name: add yum versionlock
  community.general.yum_versionlock:
    state: present
    name: "{{ package_name }}"