- name: Download RPM Packages
  vars:
    PKG_URL_SUFFIX: "{{ STACK_VERSION }}-x86_64.rpm"
    package_prefixes: "{{ RPM_PACKAGES }}"
  block:
    - name: Create Download Directory
      file:
        path: "{{ DOWNLOAD_BASE_DIR }}/{{ item }}"
        state: directory
      loop: "{{ package_prefixes }}"

    - name: Download RPM Packages
      uri:
        url: "{{ ARTIFACT_DOWNLOADS_BASE_URL }}/{{ item }}-{{ PKG_URL_SUFFIX }}"
        dest: "{{ DOWNLOAD_BASE_DIR }}/{{ item }}/{{ PKG_URL_SUFFIX }}"
        method: GET
        status_code:
          - 200
          - 304
          - 404
      loop: "{{ package_prefixes }}"