- name: Download Packages
  include_tasks: download_packages.yml
  loop_control:
    loop_var: os_item
  with_items:
    - { os: "linux", package_type: "tar.gz" }
    - { os: "windows", package_type: "zip" }

- name: Download RPM Packages (Linux Only)
  include_tasks: download_rpm_packages.yml
  when: "'{{ linux_distribution }}' in ansible_distribution"

- name: Download DEB Packages (Linux Only)
  include_tasks: download_deb_packages.yml
  when: "'{{ linux_distribution }}' in ansible_distribution"