- name: get cluster version
  uri:
    url: https://{{ elastic_hostname }}:9200
    method: GET
    return_content: true
    user: "{{ elastic_user }}"
    password: "{{ elastic_password }}"
    force_basic_auth: true
    validate_certs: false
    ca_path: /etc/elasticsearch/certs/http_ca.crt
  register: elasticsearch_result
  retries: 5
  delay: 30

- name: set cluster version variable
  set_fact:
    current_elasticsearch_version: "{{ elasticsearch_result.json.version.number }}"