- name: get cluster version
  uri:
    url: https://{{ inventory_hostname }}:9200
    method: GET
    return_content: true
    user: "{{ elastic_user }}"
    password: "{{ elastic_password }}"
    force_basic_auth: true
    ca_path: /etc/elasticsearch/certs/http_ca.crt
  register: elasticsearch_result
  retries: 3
  delay: 10

- name: set cluster version variable
  set_fact:
    current_elasticsearch_version: "{{ elasticsearch_result.json.version.number }}"

- name: check available versions
  yum:
    name: elasticsearch.x86_64
    state: latest
  check_mode: true
  register: yum_latest_versions
  failed_when: yum_latest_versions.changed == false