- name: Get cluster version
  uri:
    url: https://{{ inventory_hostname }}:9200
    method: GET
    return_content: true
    user: "{{ elastic_user }}"
    password: "{{ elastic_password }}"
    force_basic_auth: true
    validate_certs: false
  register: elasticsearch_result
  retries: 3
  delay: 10

- debug:
    var: elasticsearch_result

- name: Set cluster version variable
  set_fact:
    current_elasticsearch_version: "{{ elasticsearch_result.json.version.number }}"

- name: Check available versions
  yum:
    name: elasticsearch.x86_64
    state: latest
  check_mode: true
  register: yum_latest_versions

- debug:
    var: yum_latest_versions