- name: stop {{ elastic_component }} on node
  systemd:
    name: "{{ elastic_component }}"
    state: stopped

- name: remove yum versionlock
  community.general.yum_versionlock:
    state: absent
    name: "{{ elastic_component }}"
  when: yum_latest_versions.changed == true

- name: upgrade {{ elastic_component }} to latest
  package:
    name: "{{ elastic_component }}"
    state: latest
  when: yum_latest_versions.changed == true

- name: reboot host
  reboot:
    reboot_timeout: 300
  when: yum_updates.results.updated|flatten|select('regex', '^kernel$') is any

- name: systemctl daemon-reload
  systemd:
    daemon_reload: true

- name: add yum versionlock
  community.general.yum_versionlock:
    state: present
    name: "{{ elastic_component }}"

- name: start {{ elastic_component }} on node
  systemd:
    name: "{{ elastic_component }}"
    state: started