- name: stop {{ elastic_component }} on node
  systemd:
    name: "{{ elastic_component }}"
    state: stopped

- name: remove yum versionlock
  community.general.yum_versionlock:
    state: absent
    name: "{{ elastic_component }}"

- name: upgrade {{ elastic_component }} to latest
  package:
    name: "{{ elastic_component }}"
    state: latest

- name: systemctl daemon-reload
  systemd:
    daemon_reload: true

- name: add yum versionlock
  community.general.yum_versionlock:
    state: present
    name: "{{ elastic_component }}"

- name: start {{ elastic_component }} on node
  systemd:
    name: "{{ elastic_component }}"
    state: started