- name: update all packages (please be patient)
  yum:
    name: '*'
    state: latest
    exclude: "{{ package_name }}"
  register: yum_updates

- debug:
    var: yum_updates

- name: Check if reboot_required
  shell:
    cmd: "needs-restarting -r"
  changed_when: false
  failed_when: reboot_required.rc != 0 and reboot_required.rc != 1
  check_mode: false
  register: reboot_required

- debug:
    var: reboot_required

- name: check available versions
  yum:
    name: "{{ package_name }}"
    state: latest
  check_mode: true
  register: yum_latest_versions
  failed_when: yum_latest_versions.changed == false and yum_updates.results|flatten|select('regex', 'kernel') is none